/*
 * Copyright (C) 2020 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#pragma once

#define KERNEL_TIMESTAMP_EVENT_GLOBAL_START_OFFSET (1)
#define KERNEL_TIMESTAMP_EVENT_GLOBAL_END_OFFSET (3)
#define KERNEL_TIMESTAMP_EVENT_CONTEXT_START_OFFSET (0)
#define KERNEL_TIMESTAMP_EVENT_CONTEXT_END_OFFSET (2)
