#
# Copyright (C) 2018-2023 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

set(NEO_OCL_VERSION_MAJOR 19)
set(NEO_OCL_VERSION_MINOR 32)

if(NOT DEFINED NEO_VERSION_BUILD)
  set(NEO_VERSION_BUILD 13826)
endif()

set(NEO_OCL_DRIVER_VERSION "${NEO_OCL_VERSION_MAJOR}.${NEO_OCL_VERSION_MINOR}.${NEO_VERSION_BUILD}")
