FROM fedora:28
MAINTAINER Jacek Danecki <jacek.danecki@intel.com>

COPY neo /root/neo

RUN dnf install -y gcc-c++ cmake ninja-build git pkg-config
RUN dnf install -y 'dnf-command(copr)'
RUN dnf copr enable -y arturh/intel-opencl
RUN dnf install -y intel-igc-opencl-devel 
RUN cd /root; git clone --depth 1 https://github.com/intel/gmmlib gmmlib
RUN mkdir /root/build; cd /root/build ; cmake -G Ninja ../neo; \
    ninja -j `nproc`
CMD ["/bin/bash"]
