FROM fedora:34
LABEL maintainer="jacek.danecki@intel.com"

COPY neo /root/neo

RUN df -h; dnf install -y gcc-c++ cmake ninja-build git pkg-config; \
    dnf install -y 'dnf-command(copr)'; \
    dnf copr enable -y jdanecki/intel-opencl; \
    dnf copr enable -y jdanecki/intel-opencl-ci; \
    dnf --showduplicate list intel-igc-opencl-devel intel-gmmlib-devel; \
    dnf install -y intel-igc-opencl-devel intel-gmmlib-devel; \
    df -h; mkdir /root/build; cd /root/build ; cmake -G Ninja \
    -DSUPPORT_GEN8=1 -DSUPPORT_GEN9=0 -DSUPPORT_GEN11=1 -DSUPPORT_GEN12LP=1 \
    -DBUILD_WITH_L0=FALSE -DDO_NOT_RUN_AUB_TESTS=1 -DDONT_CARE_OF_VIRTUALS=1 \
    -DUSE_ULT_PCH=1 ../neo; \
    ninja -j 2  && du -sh && cd .. && rm -rf build
CMD ["/bin/bash"]
