FROM docker.io/base/archlinux
MAINTAINER Jacek Danecki <jacek.danecki@intel.com>

COPY neo /root/neo
COPY scripts/prepare-arch-gcc-5.sh /root
COPY scripts/build-arch-dep.sh /root
COPY scripts/prepare-workspace.sh /root

RUN /root/prepare-arch-gcc-5.sh
RUN /root/prepare-workspace.sh
RUN cd /root/build ; cmake -G Ninja -DBUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 ../neo; \
    ninja -j `nproc`
CMD ["/bin/bash"]
