#
# Copyright (C) 2019 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

get_property(NEO_CORE_GMM_HELPER GLOBAL PROPERTY NEO_CORE_GMM_HELPER)
target_sources(${NEO_STATIC_LIB_NAME} PRIVATE ${NEO_CORE_GMM_HELPER})

get_property(NEO_CORE_SKU_INFO_BASE GLOBAL PROPERTY NEO_CORE_SKU_INFO_BASE)
target_sources(${NEO_STATIC_LIB_NAME} PRIVATE ${NEO_CORE_SKU_INFO_BASE})

if(WIN32)
  get_property(NEO_CORE_SKU_INFO_WINDOWS GLOBAL PROPERTY NEO_CORE_SKU_INFO_WINDOWS)
  target_sources(${NEO_STATIC_LIB_NAME} PRIVATE ${NEO_CORE_SKU_INFO_WINDOWS})
endif()