#
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

set(L0_NOT_SUPPORTED_PRODUCT_FAMILIES
    "IGFX_GEMINILAKE"
    "IGFX_BROXTON"
    "IGFX_LAKEFIELD"
    "IGFX_ELKHARTLAKE"
    "IGFX_BROADWELL"
)
