components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: bf373b78d59642658ea7138b7600001fb57c0031
    type: git
  gmmlib:
    asset_name: gmmlib
    dest_dir: gmmlib
    type: git
    branch: master
    revision: intel-gmmlib-22.10.0
    repository: https://github.com/intel/gmmlib.git
  igc:
    asset_name: igc
    dest_dir: igc
    type: git
    branch: releases/2.32.x
    revision: ed2024120322e39916e349a3503cb89f9395f9f4
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    asset_name: igsc
    dest_dir: igsc
    type: git
    branch: master
    revision: V0.9.5
    repository: https://github.com/intel/igsc.git
    component_version: 301
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 4091-6371
  level_zero:
    asset_name: level_zero
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.28.2
    repository: https://github.com/oneapi-src/level-zero
  libva:
    asset_name: libva
    dest_dir: libva
    type: git
    branch: v2.2-branch
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    asset_name: metrics-discovery
    dest_dir: metrics/discovery
    type: git
    branch: master
    revision: 1.14.185
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    asset_name: metrics-library
    dest_dir: metrics/library
    type: git
    branch: master
    revision: 1.0.209.1
    repository: https://github.com/intel/metrics-library.git
  neo-clang-format:
    dest_dir: tools/clang-format
    type: git
    branch: clang-format
    revision: 22.1.1
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: e7470d744ccd66ab0356f497b829dbca3108e5e2-4056
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-4091
include:
- aub_configs.yml
- infra.yml
version: '1'
