/*
 * Copyright (C) 2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#include "shared/test/common/test_macros/hw_test_base.h"
using namespace NEO;

HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, whenQueryingMaxNumSamplersThenReturnSixteen, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenGettingDefaultCopyEngineThenEngineBCSIsReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAdjustingEnginesGroupThenDoNotChangeEngineGroups, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, whenAskingForLocalDispatchSizeThenReturnEmpty, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AubFileStreamTests, whenCreateFullFilePathIsCalledThenFileNameIsCorrect_IsAtLeastXe2HpgCore, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AubHelperTest, WhenHBMSizePerTileInGigabytesIsNotSetThenGetMemBankSizeReturnsCorrectValue, criProductEnumValue);

HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, whenGetGpgpuEnginesThenReturnTwoCccsEnginesAndFourCcsEnginesAndEightLinkCopyEnginesAndTwoRegularCopyEngines, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, givenOneBcsEnabledWhenGetEnginesCalledThenCreateOnlyOneBcs, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, givenDebugFlagDisablingContextGroupWhenQueryingEnginesThenLowPriorityAndInternalEngineIsReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, givenContextGroupWhenQueryingEnginesThenLowPriorityHighPriorityAndInternalEngineIsReturned, criProductEnumValue);

HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenIsImplicitScalingSupportedThenExpectFalse_IsNotXeHpcCore, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenPatIndexWhenCheckIsCoherentAllocationThenReturnProperValue_IsAtLeastXe2HpgCore, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskedIfPageFaultIsSupportedThenReturnFalse, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingForDeviceToHostCopySignalingFenceFalseReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenCheckingIs2MBLocalMemAlignmentEnabledThenCorrectValueIsReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingForSharingWith3dOrMediaSupportThenTrueReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTestXe3pCore, givenGrfCount512WhenHeaplessModeDisabledThenAdjustedMaxThreadsPerThreadGroup, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingShouldRegisterEnqueuedWalkerWithProfilingThenFalseReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingIsInterruptSupportedThenFalseReturned, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingIsMediaContextSupportedThenFalseReturned, criProductEnumValue);
