/*
 * Copyright (C) 2025-2026 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#include "shared/test/common/test_macros/hw_test_base.h"
using namespace NEO;

HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, whenQueryingMaxNumSamplersThenReturnSixteen, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenGettingDefaultCopyEngineThenEngineBCSIsReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAdjustingEnginesGroupThenDoNotChangeEngineGroups, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, whenAskingForLocalDispatchSizeThenReturnEmpty, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AubFileStreamTests, whenCreateFullFilePathIsCalledThenFileNameIsCorrect_IsAtLeastXe2HpgCore, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AubHelperTest, WhenHBMSizePerTileInGigabytesIsNotSetThenGetMemBankSizeReturnsCorrectValue, IGFX_CRI);

HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, whenGetGpgpuEnginesThenReturnTwoCccsEnginesAndFourCcsEnginesAndEightLinkCopyEnginesAndTwoRegularCopyEngines, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, givenOneBcsEnabledWhenGetEnginesCalledThenCreateOnlyOneBcs, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, givenDebugFlagDisablingContextGroupWhenQueryingEnginesThenLowPriorityAndInternalEngineIsReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(GfxCoreHelperTestsXe3pCore, givenContextGroupWhenQueryingEnginesThenLowPriorityHighPriorityAndInternalEngineIsReturned, IGFX_CRI);

HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenIsImplicitScalingSupportedThenExpectFalse_IsNotXeHpcCore, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenPatIndexWhenCheckIsCoherentAllocationThenReturnProperValue_IsAtLeastXe2HpgCore, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskedIfPageFaultIsSupportedThenReturnFalse, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingForDeviceToHostCopySignalingFenceFalseReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenCheckingIs2MBLocalMemAlignmentEnabledThenCorrectValueIsReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingForSharingWith3dOrMediaSupportThenTrueReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTestXe3pCore, givenGrfCount512WhenHeaplessModeDisabledThenAdjustedMaxThreadsPerThreadGroup, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingShouldRegisterEnqueuedWalkerWithProfilingThenFalseReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingIsInterruptSupportedThenFalseReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenAskingIsMediaContextSupportedThenFalseReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenGettingPreferredWorkgroupCountPerSubsliceThenZeroReturned, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenProductHelperWhenGetL1CachePolicyThenReturnWriteByPass_IsSbaRequiredAndAtLeastXeCore, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(ProductHelperTest, givenAtLeastXe3pCoreWhenGetL1CachePolicyThenReturnCorrectValue_IsAtLeastXe3pCore, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(CompilerProductHelperFixture, givenAtLeastXeHpgCoreWhenGetCachingPolicyOptionsThenReturnWriteByPassPolicyOption_IsAtLeastXeCore, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(SbaTest, givenStateBaseAddressAndDebugFlagSetWhenAppendExtraCacheSettingsThenProgramCorrectL1CachePolicy_IsSbaRequiredAndAtLeastXeCore, IGFX_CRI);
