/*
 * Copyright (C) 2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#include "shared/source/xe3p_core/hw_cmds_cri.h"
#include "shared/test/common/test_macros/hw_test_base.h"
using namespace NEO;

HWTEST_EXCLUDE_PRODUCT(AUBWriteImageBCS, GivenUnalignedMemoryWhenWritingImageWithBlitterEnabledThenExpectationsAreMet, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBCopyImageCCS, WhenCopyingThenExpectationsMet, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBCopyImageBCS, WhenCopyingWithBlitterEnabledThenExpectationsMet, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageCCS, GivenMisalignedHostPtrWhenReadingImageThenExpectationsAreMet_ImageSupport, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageCCS, GivenUnalignedMemoryWhenReadingImageThenExpectationsAreMet, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageBCS, GivenMisalignedHostPtrWhenReadingImageWithBlitterEnabledThenExpectationsAreMet_ImageSupport, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageBCS, GivenUnalignedMemoryWhenReadingImageWithBlitterEnabledThenExpectationsAreMet, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBWriteImageCCS, GivenMisalignedHostPtrWhenWritingImageThenExpectationsAreMet_ImageSupport, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBWriteImageCCS, GivenUnalignedMemoryWhenWritingImageThenExpectationsAreMet, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(AUBWriteImageBCS, GivenMisalignedHostPtrWhenWritingImageWithBlitterEnabledThenExpectationsAreMet_ImageSupport, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenNotCompressedBufferWhenBltExecutedThenCompressDataAndResolve, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenHostPtrWhenBlitCommandToCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenDstHostPtrWhenBlitCommandFromCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenDstHostPtrWhenBlitCommandFromNotCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenSrcHostPtrWhenBlitCommandToNotCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenBufferWithOffsetWhenHostPtrBlitCommandIsDispatchedFromHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenBufferWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenOffsetsWhenBltExecutedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenSrcCompressedBufferWhenBlitCommandToDstCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenCompressedBufferWhenAuxTranslationCalledThenResolveAndCompress, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenReadBufferRectWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenWriteBufferRectWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenCopyBufferRectWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineTests, givenCopyBufferRectWithBigSizesWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileCopyEngineSystemMemoryTests, givenSrcSystemBufferWhenBlitCommandToDstSystemBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenNotCompressedBufferWhenBltExecutedThenCompressDataAndResolve, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenHostPtrWhenBlitCommandToCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenDstHostPtrWhenBlitCommandFromCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenDstHostPtrWhenBlitCommandFromNotCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenSrcHostPtrWhenBlitCommandToNotCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenBufferWithOffsetWhenHostPtrBlitCommandIsDispatchedFromHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenBufferWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenOffsetsWhenBltExecutedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenSrcCompressedBufferWhenBlitCommandToDstCompressedBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenCompressedBufferWhenAuxTranslationCalledThenResolveAndCompress, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenReadBufferRectWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenWriteBufferRectWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileXe3pCoreTests, givenCopyBufferRectWithOffsetWhenHostPtrBlitCommandIsDispatchedToHostPtrThenDataIsCorrectlyCopied, criProductEnumValue);
HWTEST_EXCLUDE_PRODUCT(SingleTileSystemMemoryXe3pCoreTests, givenSrcSystemBufferWhenBlitCommandToDstSystemBufferIsDispatchedThenCopiedDataIsValid, criProductEnumValue);
