/*
 * Copyright (C) 2025-2026 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#include "shared/source/xe3p_core/hw_cmds_cri.h"
#include "shared/test/common/test_macros/hw_test_base.h"
using namespace NEO;

HWTEST_EXCLUDE_PRODUCT(AUBWriteImageBCS, GivenUnalignedMemoryWhenWritingImageWithBlitterEnabledThenExpectationsAreMet, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBCopyImageCCS, WhenCopyingThenExpectationsMet, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBCopyImageBCS, WhenCopyingWithBlitterEnabledThenExpectationsMet, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageCCS, GivenMisalignedHostPtrWhenReadingImageThenExpectationsAreMet_ImageSupport, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageCCS, GivenUnalignedMemoryWhenReadingImageThenExpectationsAreMet, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageBCS, GivenMisalignedHostPtrWhenReadingImageWithBlitterEnabledThenExpectationsAreMet_ImageSupport, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBReadImageBCS, GivenUnalignedMemoryWhenReadingImageWithBlitterEnabledThenExpectationsAreMet, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBWriteImageCCS, GivenMisalignedHostPtrWhenWritingImageThenExpectationsAreMet_ImageSupport, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBWriteImageCCS, GivenUnalignedMemoryWhenWritingImageThenExpectationsAreMet, IGFX_CRI);
HWTEST_EXCLUDE_PRODUCT(AUBWriteImageBCS, GivenMisalignedHostPtrWhenWritingImageWithBlitterEnabledThenExpectationsAreMet_ImageSupport, IGFX_CRI);
