/*
 * Copyright (C) 2018-2026 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#if SUPPORT_XE3P_CORE
#ifdef SUPPORT_CRI
DEVICE(0x674C, IGFX_CRI)
DEVICE(0x674D, IGFX_CRI)
DEVICE(0x674E, IGFX_CRI)
DEVICE(0x674F, IGFX_CRI)
DEVICE(0x6750, IGFX_CRI)
#endif
#ifdef SUPPORT_NVLP
DEVICE(0xD750, IGFX_NVL)
DEVICE(0xD751, IGFX_NVL)
DEVICE(0xD752, IGFX_NVL)
DEVICE(0xD753, IGFX_NVL)
DEVICE(0xD754, IGFX_NVL)
DEVICE(0xD755, IGFX_NVL)
DEVICE(0xD756, IGFX_NVL)
DEVICE(0xD757, IGFX_NVL)
DEVICE(0xD75F, IGFX_NVL)
DEVICE(0xD74A, IGFX_NVL)
DEVICE(0xD74B, IGFX_NVL)
#endif
#endif

#if SUPPORT_XE3_CORE
#ifdef SUPPORT_PTL
NAMEDDEVICE(0xB080, IGFX_PTL, "Intel(R) Arc(TM) B390 GPU")
NAMEDDEVICE(0xB081, IGFX_PTL, "Intel(R) Arc(TM) B370 GPU")
NAMEDDEVICE(0xB082, IGFX_PTL, "Intel(R) Arc(TM) B390 GPU")
NAMEDDEVICE(0xB083, IGFX_PTL, "Intel(R) Arc(TM) B370 GPU")
DEVICE(0xB084, IGFX_PTL)
DEVICE(0xB085, IGFX_PTL)
DEVICE(0xB086, IGFX_PTL)
DEVICE(0xB087, IGFX_PTL)
NAMEDDEVICE(0xB08F, IGFX_PTL, "Intel(R) Graphics")
NAMEDDEVICE(0xB090, IGFX_PTL, "Intel(R) Graphics")
NAMEDDEVICE(0xB0A0, IGFX_PTL, "Intel(R) Graphics")
DEVICE(0xB0B0, IGFX_PTL)
NAMEDDEVICE(0xFD80, IGFX_PTL, "Intel(R) Graphics")
NAMEDDEVICE(0xFD81, IGFX_PTL, "Intel(R) Graphics")
#endif
#ifdef SUPPORT_NVLS
DEVICE(0xD740, IGFX_NVL_XE3G)
DEVICE(0xD741, IGFX_NVL_XE3G)
DEVICE(0xD742, IGFX_NVL_XE3G)
DEVICE(0xD743, IGFX_NVL_XE3G)
DEVICE(0xD744, IGFX_NVL_XE3G)
DEVICE(0xD745, IGFX_NVL_XE3G)
#endif
#endif

#if SUPPORT_XE2_HPG_CORE
#ifdef SUPPORT_BMG
DEVICE(0xE202, IGFX_BMG)
NAMEDDEVICE(0xE209, IGFX_BMG, "Intel(R) Arc(TM) B580 Graphics")
NAMEDDEVICE(0xE20B, IGFX_BMG, "Intel(R) Arc(TM) B580 Graphics")
NAMEDDEVICE(0xE20C, IGFX_BMG, "Intel(R) Arc(TM) B570 Graphics")
DEVICE(0xE20D, IGFX_BMG)
DEVICE(0xE210, IGFX_BMG)
NAMEDDEVICE(0xE211, IGFX_BMG, "Intel(R) Arc(TM) Pro B60 Graphics")
NAMEDDEVICE(0xE212, IGFX_BMG, "Intel(R) Arc(TM) Pro B50 Graphics")
DEVICE(0xE215, IGFX_BMG)
DEVICE(0xE216, IGFX_BMG)
DEVICE(0xE220, IGFX_BMG)
DEVICE(0xE221, IGFX_BMG)
NAMEDDEVICE(0xE222, IGFX_BMG, "Intel(R) Arc(TM) Pro B65 Graphics")
NAMEDDEVICE(0xE223, IGFX_BMG, "Intel(R) Arc(TM) Pro B70 Graphics")
#endif
#ifdef SUPPORT_LNL
NAMEDDEVICE(0x6420, IGFX_LUNARLAKE, "Intel(R) Graphics")
NAMEDDEVICE(0x64A0, IGFX_LUNARLAKE, "Intel(R) Arc(TM) Graphics")
NAMEDDEVICE(0x64B0, IGFX_LUNARLAKE, "Intel(R) Graphics")
#endif
#endif

#if SUPPORT_XE_HPC_CORE
#ifdef SUPPORT_PVC
DEVICE(0x0BD0, IGFX_PVC)
NAMEDDEVICE(0x0BD5, IGFX_PVC, "Intel(R) Data Center GPU Max 1550")
NAMEDDEVICE(0x0BD6, IGFX_PVC, "Intel(R) Data Center GPU Max 1550")
NAMEDDEVICE(0x0BD7, IGFX_PVC, "Intel(R) Data Center GPU Max 1350")
NAMEDDEVICE(0x0BD8, IGFX_PVC, "Intel(R) Data Center GPU Max 1350")
NAMEDDEVICE(0x0BD9, IGFX_PVC, "Intel(R) Data Center GPU Max 1100")
NAMEDDEVICE(0x0BDA, IGFX_PVC, "Intel(R) Data Center GPU Max 1100")
NAMEDDEVICE(0x0BDB, IGFX_PVC, "Intel(R) Data Center GPU Max 1100")
NAMEDDEVICE(0x0B69, IGFX_PVC, "Intel(R) Data Center GPU Max 1450")
NAMEDDEVICE(0x0B6E, IGFX_PVC, "Intel(R) Data Center GPU Max 1100C")
NAMEDDEVICE(0x0BD4, IGFX_PVC, "Intel(R) Data Center GPU Max 1550VG")
#endif
#endif

#ifdef SUPPORT_XE_HPG_CORE
#ifdef SUPPORT_DG2
DEVICE(0x4F80, IGFX_DG2)
DEVICE(0x4F81, IGFX_DG2)
DEVICE(0x4F82, IGFX_DG2)
DEVICE(0x4F83, IGFX_DG2)
DEVICE(0x4F84, IGFX_DG2)
DEVICE(0x4F85, IGFX_DG2)
DEVICE(0x4F86, IGFX_DG2)
DEVICE(0x4F87, IGFX_DG2)
DEVICE(0x4F88, IGFX_DG2)
NAMEDDEVICE(0x5690, IGFX_DG2, "Intel(R) Arc(TM) A770M Graphics")
NAMEDDEVICE(0x5691, IGFX_DG2, "Intel(R) Arc(TM) A730M Graphics")
NAMEDDEVICE(0x5692, IGFX_DG2, "Intel(R) Arc(TM) A550M Graphics")
NAMEDDEVICE(0x5693, IGFX_DG2, "Intel(R) Arc(TM) A370M Graphics")
NAMEDDEVICE(0x5694, IGFX_DG2, "Intel(R) Arc(TM) A350M Graphics")
DEVICE(0x5695, IGFX_DG2)
NAMEDDEVICE(0x5696, IGFX_DG2, "Intel(R) Arc(TM) A570M Graphics")
NAMEDDEVICE(0x5697, IGFX_DG2, "Intel(R) Arc(TM) A530M Graphics")
DEVICE(0x56A3, IGFX_DG2)
DEVICE(0x56A4, IGFX_DG2)
NAMEDDEVICE(0x56B0, IGFX_DG2, "Intel(R) Arc(TM) Pro A30M Graphics")
NAMEDDEVICE(0x56B1, IGFX_DG2, "Intel(R) Arc(TM) Pro A40/A50 Graphics")
NAMEDDEVICE(0x56B2, IGFX_DG2, "Intel(R) Arc(TM) Pro A60M Graphics")
NAMEDDEVICE(0x56B3, IGFX_DG2, "Intel(R) Arc(TM) Pro A60 Graphics")
NAMEDDEVICE(0x56BA, IGFX_DG2, "Intel(R) Arc(TM) A380E Graphics")
NAMEDDEVICE(0x56BB, IGFX_DG2, "Intel(R) Arc(TM) A310E Graphics")
NAMEDDEVICE(0x56BC, IGFX_DG2, "Intel(R) Arc(TM) A370E Graphics")
NAMEDDEVICE(0x56BD, IGFX_DG2, "Intel(R) Arc(TM) A350E Graphics")
NAMEDDEVICE(0x56BE, IGFX_DG2, "Intel(R) Arc(TM) A750E Graphics")
NAMEDDEVICE(0x56BF, IGFX_DG2, "Intel(R) Arc(TM) A580E Graphics")
NAMEDDEVICE(0x56A0, IGFX_DG2, "Intel(R) Arc(TM) A770 Graphics")
NAMEDDEVICE(0x56A1, IGFX_DG2, "Intel(R) Arc(TM) A750 Graphics")
NAMEDDEVICE(0x56A2, IGFX_DG2, "Intel(R) Arc(TM) A580 Graphics")
NAMEDDEVICE(0x56A5, IGFX_DG2, "Intel(R) Arc(TM) A380 Graphics")
NAMEDDEVICE(0x56A6, IGFX_DG2, "Intel(R) Arc(TM) A310 LP Graphics")
NAMEDDEVICE(0x56AF, IGFX_DG2, "Intel(R) Arc(TM) A760A Graphics")
NAMEDDEVICE(0x56C0, IGFX_DG2, "Intel(R) Data Center GPU Flex 170")
NAMEDDEVICE(0x56C1, IGFX_DG2, "Intel(R) Data Center GPU Flex 140")
NAMEDDEVICE(0x56C2, IGFX_DG2, "Intel(R) Data Center GPU Flex 170V")
#endif
#ifdef SUPPORT_MTL
NAMEDDEVICE(0x7D40, IGFX_METEORLAKE, "Intel(R) Graphics")
NAMEDDEVICE(0x7D55, IGFX_METEORLAKE, "Intel(R) Arc(TM) Graphics")
NAMEDDEVICE(0x7DD5, IGFX_METEORLAKE, "Intel(R) Graphics")
NAMEDDEVICE(0x7D45, IGFX_METEORLAKE, "Intel(R) Graphics")
#endif
#ifdef SUPPORT_ARL
NAMEDDEVICE(0x7D67, IGFX_ARROWLAKE, "Intel(R) Graphics")
NAMEDDEVICE(0x7D51, IGFX_ARROWLAKE, "Intel(R) Arc(TM) Graphics")
NAMEDDEVICE(0x7DD1, IGFX_ARROWLAKE, "Intel(R) Graphics")
NAMEDDEVICE(0x7D41, IGFX_ARROWLAKE, "Intel(R) Graphics")
#endif
#endif

#ifdef SUPPORT_GEN12LP

#ifdef SUPPORT_TGLLP
NAMEDDEVICE(0x9A49, IGFX_TIGERLAKE_LP, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0x9A40, IGFX_TIGERLAKE_LP, "Intel(R) Iris(R) Xe Graphics")
DEVICE(0x9A59, IGFX_TIGERLAKE_LP)
NAMEDDEVICE(0x9A60, IGFX_TIGERLAKE_LP, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x9A68, IGFX_TIGERLAKE_LP, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x9A70, IGFX_TIGERLAKE_LP, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x9A78, IGFX_TIGERLAKE_LP, "Intel(R) UHD Graphics")
#endif

#ifdef SUPPORT_DG1
NAMEDDEVICE(0x4905, IGFX_DG1, "Intel(R) Iris(R) Xe MAX Graphics")
DEVICE(0x4906, IGFX_DG1)
NAMEDDEVICE(0x4907, IGFX_DG1, "Intel(R) Server GPU SG-18M")
NAMEDDEVICE(0x4908, IGFX_DG1, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0x4909, IGFX_DG1, "Intel(R) Iris(R) Xe MAX 100 Graphics")
#endif

#ifdef SUPPORT_RKL
DEVICE(0x4C80, IGFX_ROCKETLAKE)
NAMEDDEVICE(0x4C8A, IGFX_ROCKETLAKE, "Intel(R) UHD Graphics 750")
NAMEDDEVICE(0x4C8B, IGFX_ROCKETLAKE, "Intel(R) UHD Graphics 730")
DEVICE(0x4C8C, IGFX_ROCKETLAKE)
NAMEDDEVICE(0x4C90, IGFX_ROCKETLAKE, "Intel(R) UHD Graphics P750")
DEVICE(0x4C9A, IGFX_ROCKETLAKE)
#endif

#ifdef SUPPORT_ADLS
NAMEDDEVICE(0x4680, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 770")
NAMEDDEVICE(0x4682, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 730")
NAMEDDEVICE(0x4688, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x468A, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x468B, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x4690, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 770")
NAMEDDEVICE(0x4692, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 730")
NAMEDDEVICE(0x4693, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 710")
NAMEDDEVICE(0xA780, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 770")
DEVICE(0xA781, IGFX_ALDERLAKE_S)
NAMEDDEVICE(0xA782, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics 730")
DEVICE(0xA783, IGFX_ALDERLAKE_S)
NAMEDDEVICE(0xA788, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics")
DEVICE(0xA789, IGFX_ALDERLAKE_S)
NAMEDDEVICE(0xA78A, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics")
NAMEDDEVICE(0xA78B, IGFX_ALDERLAKE_S, "Intel(R) UHD Graphics")
#endif

#ifdef SUPPORT_ADLN
NAMEDDEVICE(0x46D0, IGFX_ALDERLAKE_N, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x46D1, IGFX_ALDERLAKE_N, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x46D2, IGFX_ALDERLAKE_N, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x46D3, IGFX_ALDERLAKE_N, "Intel(R) Graphics")
NAMEDDEVICE(0x46D4, IGFX_ALDERLAKE_N, "Intel(R) Graphics")
#endif

#ifdef SUPPORT_ADLP
DEVICE(0x46A0, IGFX_ALDERLAKE_P)
DEVICE(0x46B0, IGFX_ALDERLAKE_P)
DEVICE(0x46A1, IGFX_ALDERLAKE_P)
NAMEDDEVICE(0x46A3, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x46A6, IGFX_ALDERLAKE_P, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0x46A8, IGFX_ALDERLAKE_P, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0x46AA, IGFX_ALDERLAKE_P, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0x462A, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x4626, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0x4628, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
DEVICE(0x46B1, IGFX_ALDERLAKE_P)
NAMEDDEVICE(0x46B3, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
DEVICE(0x46C0, IGFX_ALDERLAKE_P)
DEVICE(0x46C1, IGFX_ALDERLAKE_P)
NAMEDDEVICE(0x46C3, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
// RPL-P
NAMEDDEVICE(0xA7A0, IGFX_ALDERLAKE_P, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0xA720, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0xA7A8, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0xA7A1, IGFX_ALDERLAKE_P, "Intel(R) Iris(R) Xe Graphics")
NAMEDDEVICE(0xA721, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0xA7A9, IGFX_ALDERLAKE_P, "Intel(R) UHD Graphics")
NAMEDDEVICE(0xA7AA, IGFX_ALDERLAKE_P, "Intel(R) Graphics")
NAMEDDEVICE(0xA7AB, IGFX_ALDERLAKE_P, "Intel(R) Graphics")
NAMEDDEVICE(0xA7AC, IGFX_ALDERLAKE_P, "Intel(R) Graphics")
NAMEDDEVICE(0xA7AD, IGFX_ALDERLAKE_P, "Intel(R) Graphics")
#endif
#endif
