/*
 * Copyright (C) 2021-2026 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#if SUPPORT_XE3P_CORE
#ifdef SUPPORT_CRI
DEVICE_CONFIG(CRI_A0, IGFX_CRI, criDeviceIds, XE3P_FAMILY, XE3P_XPC_RELEASE)
#endif
#ifdef SUPPORT_NVLP
DEVICE_CONFIG(NVL_P_A0, IGFX_NVL, nvlPDeviceIds, XE3P_FAMILY, XE3P_LPG_RELEASE)
DEVICE_CONFIG(NVL_P_B0, IGFX_NVL, nvlPDeviceIds, XE3P_FAMILY, XE3P_LPG_RELEASE)
#endif
#endif

#if SUPPORT_XE3_CORE
#ifdef SUPPORT_PTL
DEVICE_CONFIG(WCL_A0, IGFX_PTL, wclDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(WCL_A1, IGFX_PTL, wclDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(PTL_H_A0, IGFX_PTL, ptlHDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(PTL_H_B0, IGFX_PTL, ptlHDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(PTL_U_A0, IGFX_PTL, ptlUDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
#endif
#ifdef SUPPORT_NVLS
DEVICE_CONFIG(NVL_U_A0, IGFX_NVL_XE3G, nvlUDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(NVL_U_A1, IGFX_NVL_XE3G, nvlUDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(NVL_U_B0, IGFX_NVL_XE3G, nvlUDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(NVL_S_A0, IGFX_NVL_XE3G, nvlSDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
DEVICE_CONFIG(NVL_S_B0, IGFX_NVL_XE3G, nvlSDeviceIds, XE3_FAMILY, XE3_LPG_RELEASE)
#endif
#endif

#if SUPPORT_XE2_HPG_CORE
#ifdef SUPPORT_BMG
DEVICE_CONFIG(BMG_G31_A0, IGFX_BMG, bmgG31DeviceIds, XE2_FAMILY, XE2_HPG_RELEASE)
DEVICE_CONFIG(BMG_G21_A0, IGFX_BMG, bmgG21DeviceIds, XE2_FAMILY, XE2_HPG_RELEASE)
#endif
#ifdef SUPPORT_LNL
DEVICE_CONFIG(LNL_A0, IGFX_LUNARLAKE, lnlDeviceIds, XE2_FAMILY, XE2_LPG_RELEASE)
DEVICE_CONFIG(LNL_A1, IGFX_LUNARLAKE, lnlDeviceIds, XE2_FAMILY, XE2_LPG_RELEASE)
DEVICE_CONFIG(LNL_B0, IGFX_LUNARLAKE, lnlDeviceIds, XE2_FAMILY, XE2_LPG_RELEASE)
#endif
#endif

#if SUPPORT_XE_HPC_CORE
#ifdef SUPPORT_PVC
DEVICE_CONFIG(PVC_XL_A0, IGFX_PVC, pvcXlDeviceIds, XE_FAMILY, XE_HPC_RELEASE)
DEVICE_CONFIG(PVC_XL_A0P, IGFX_PVC, pvcXlDeviceIds, XE_FAMILY, XE_HPC_RELEASE)
DEVICE_CONFIG(PVC_XT_A0, IGFX_PVC, pvcXtDeviceIds, XE_FAMILY, XE_HPC_RELEASE)
DEVICE_CONFIG(PVC_XT_B0, IGFX_PVC, pvcXtDeviceIds, XE_FAMILY, XE_HPC_RELEASE)
DEVICE_CONFIG(PVC_XT_B1, IGFX_PVC, pvcXtDeviceIds, XE_FAMILY, XE_HPC_RELEASE)
DEVICE_CONFIG(PVC_XT_C0, IGFX_PVC, pvcXtDeviceIds, XE_FAMILY, XE_HPC_RELEASE)
DEVICE_CONFIG(PVC_XT_C0_VG, IGFX_PVC, pvcXtVgDeviceIds, XE_FAMILY, XE_HPC_VG_RELEASE)

#endif
#endif

#ifdef SUPPORT_XE_HPG_CORE
#ifdef SUPPORT_MTL
DEVICE_CONFIG(MTL_U_A0, IGFX_METEORLAKE, mtlmDeviceIds, XE_FAMILY, XE_LPG_RELEASE)
DEVICE_CONFIG(MTL_U_B0, IGFX_METEORLAKE, mtlmDeviceIds, XE_FAMILY, XE_LPG_RELEASE)
DEVICE_CONFIG(MTL_H_A0, IGFX_METEORLAKE, mtlpDeviceIds, XE_FAMILY, XE_LPG_RELEASE)
DEVICE_CONFIG(MTL_H_B0, IGFX_METEORLAKE, mtlpDeviceIds, XE_FAMILY, XE_LPG_RELEASE)
#endif
#ifdef SUPPORT_DG2
DEVICE_CONFIG(DG2_G10_A0, IGFX_DG2, dg2G10DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G10_A1, IGFX_DG2, dg2G10DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G10_B0, IGFX_DG2, dg2G10DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G10_C0, IGFX_DG2, dg2G10DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G11_A0, IGFX_DG2, dg2G11DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G11_B0, IGFX_DG2, dg2G11DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G11_B1, IGFX_DG2, dg2G11DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
DEVICE_CONFIG(DG2_G12_A0, IGFX_DG2, dg2G12DeviceIds, XE_FAMILY, XE_HPG_RELEASE)
#endif
#ifdef SUPPORT_ARL
DEVICE_CONFIG(ARL_H_A0, IGFX_ARROWLAKE, arlDeviceIds, XE_FAMILY, XE_LPGPLUS_RELEASE)
DEVICE_CONFIG(ARL_H_B0, IGFX_ARROWLAKE, arlDeviceIds, XE_FAMILY, XE_LPGPLUS_RELEASE)
#endif
#endif

#ifdef SUPPORT_GEN12LP
#ifdef SUPPORT_TGLLP
DEVICE_CONFIG(TGL, IGFX_TIGERLAKE_LP, tgllpDeviceIds, XE_FAMILY, XE_LP_RELEASE)
#endif
#ifdef SUPPORT_DG1
DEVICE_CONFIG(DG1, IGFX_DG1, dg1DeviceIds, XE_FAMILY, XE_LP_RELEASE)
#endif
#ifdef SUPPORT_RKL
DEVICE_CONFIG(RKL, IGFX_ROCKETLAKE, rklDeviceIds, XE_FAMILY, XE_LP_RELEASE)
#endif
#ifdef SUPPORT_ADLS
DEVICE_CONFIG(ADL_S, IGFX_ALDERLAKE_S, adlsDeviceIds, XE_FAMILY, XE_LP_RELEASE)
#endif
#ifdef SUPPORT_ADLP
DEVICE_CONFIG(ADL_P, IGFX_ALDERLAKE_P, adlpDeviceIds, XE_FAMILY, XE_LP_RELEASE)
#endif
#ifdef SUPPORT_ADLN
DEVICE_CONFIG(ADL_N, IGFX_ALDERLAKE_N, adlnDeviceIds, XE_FAMILY, XE_LP_RELEASE)
#endif
#endif
