/*
 * Copyright (C) 2022-2025 Intel Corporation
 *
 * SPDX-License-Identifier: MIT
 *
 */

#include "shared/test/common/test_macros/hw_test_base.h"

HWTEST_EXCLUDE_PRODUCT(MiAtomicAubTest, GivenSystemMemoryWhenDispatchingAtomicMove4BytesOperationThenExpectCorrectEndValues, IGFX_XE_HPC_CORE);
HWTEST_EXCLUDE_PRODUCT(MultiContextLargeGrfKernelAubTest, givenLargeAndSmallGrfWhenParallelRunOnCcsAndRcsThenResultsAreOk, IGFX_XE_HPC_CORE);
HWTEST_EXCLUDE_PRODUCT(SingleTileDualContextTest, givenSingleAllocationWhenUpdatedFromDifferentContextThenDataIsValid_IsPVC, IGFX_XE_HPC_CORE);
HWTEST_EXCLUDE_PRODUCT(SingleTileDualContextTest, givenSingleTileAndDualContextWhenSubmittingThenDataIsValid_IsPVC, IGFX_XE_HPC_CORE);
HWTEST_EXCLUDE_PRODUCT(TwoTilesAllContextsTest, HEAVY_givenTwoTilesAndAllContextsWhenSubmittingThenDataIsValid_IsPVC, IGFX_XE_HPC_CORE);
HWTEST_EXCLUDE_PRODUCT(TwoTilesDualContextTest, givenTwoTilesAndDualContextWhenSubmittingThenDataIsValid_IsPVC, IGFX_XE_HPC_CORE);
HWTEST_EXCLUDE_PRODUCT(FourTilesDualContextTest, HEAVY_givenFourTilesAndDualContextWhenSubmittingThenDataIsValid_IsPVC, IGFX_XE_HPC_CORE);
