FROM docker.io/ubuntu:20.04
MAINTAINER Jacek Danecki <jacek.danecki@intel.com>

RUN apt-get -y update ; apt-get install -y --allow-unauthenticated --no-install-recommends gpg software-properties-common
RUN add-apt-repository -y ppa:intel-opencl/intel-opencl
RUN apt-get -y update ; apt-get install -y --allow-unauthenticated cmake g++-7 git pkg-config ninja-build libigc-dev libigdgmm-dev file

ENV CC gcc-7
ENV CXX g++-7

CMD ["/bin/bash"]
