#
# Copyright (C) 2020-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-5, gcc-6, gcc-7, gcc-8]
    env:
      WORKFLOW: CI
    steps:
    - uses: actions/checkout@v2
      with:
        path: neo
    - name: echo
      run: |
        env
    - name: prepare image
      env:
        BUILD_OS: ubuntu-18.04
        COMPILER: ${{ matrix.compiler }}
      working-directory: neo/scripts/actions
      run: ./run-action-docker-prepare.sh
    - name: build
      env:
        BUILD_OS: ubuntu-18.04
        COMPILER: ${{ matrix.compiler }}
      run: ./neo/scripts/actions/run-action-build.sh
    - name: prepare artifacts
      if: matrix.compiler == 'gcc-7'
      run: |
        mkdir artifacts
        mv build/*.deb artifacts/
    - name: upload artifacts
      if: matrix.compiler == 'gcc-7'
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: artifacts
