#
# Copyright (C) 2020-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

name: verify
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: 
          - [gcc-7, g++-7]
          - [gcc-8, g++-8]
          - [gcc-9, g++-9]
          - [gcc-10, g++-10]
      fail-fast: false
    env:
      WORKFLOW: ${{ github.workflow }}
    steps:
    - uses: actions/checkout@v2
      with:
        path: neo
    - name: prepare image
      env:
        BUILD_OS: ubuntu-20.04
      working-directory: neo/scripts/actions
      run: ./run-action-docker-prepare.sh
    - name: build
      env:
        CC: ${{ matrix.compiler[0] }}
        CXX: ${{ matrix.compiler[1] }}
        BUILD_OS: ubuntu-20.04
      run: ./neo/scripts/actions/run-action-build.sh
    - name: prepare artifacts
      if: matrix.compiler == 'gcc-7'
      run: |
        mkdir artifacts
        mv build/*.deb artifacts/
    - name: upload artifacts
      if: matrix.compiler == 'gcc-7'
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: artifacts
